name: CI Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK: ${{ secrets.CYPRESSNOTIFIER }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}

    steps:
      - name: Install jq (JSON processor)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get latest release URL
        run: |
          LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.html_url')
          echo "LATEST_RELEASE_URL=$LATEST_RELEASE_URL" >> $GITHUB_ENV
        shell: bash

      - name: Get latest Cypress test URL
        run: |
          # Obtener el ID del proyecto y el token de acceso
          CYPRESS_PROJECT_ID="${{ env.CYPRESS_PROJECT_ID }}"
          CYPRESS_RECORD_KEY="${{ env.CYPRESS_RECORD_KEY }}"

          # Obtener el ID del último run
          LATEST_RUN_ID=$(curl -s -u $CYPRESS_RECORD_KEY: https://api.cypress.io/v1/projects/$CYPRESS_PROJECT_ID/runs | jq -r '.[0].id')

          # Verificar si se obtuvo un ID válido
          if [ -z "$LATEST_RUN_ID" ] || [ "$LATEST_RUN_ID" = "null" ]; then
            echo "No se pudo obtener el ID del último run de Cypress."
          else
            # Construir la URL del Dashboard
            CYPRESS_DASHBOARD_URL="https://dashboard.cypress.io/projects/$CYPRESS_PROJECT_ID/runs/$LATEST_RUN_ID"
            echo "CYPRESS_DASHBOARD_URL=$CYPRESS_DASHBOARD_URL" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK: ${{ env.SLACK_WEBHOOK }}
          LATEST_RELEASE_URL: ${{ env.LATEST_RELEASE_URL }}
          CYPRESS_DASHBOARD_URL: ${{ env.CYPRESS_DASHBOARD_URL }}
        run: |
          MESSAGE="El último release está disponible en: $LATEST_RELEASE_URL"

          if [ -n "$CYPRESS_DASHBOARD_URL" ]; then
            MESSAGE="$MESSAGE. El último test de Cypress está disponible en: $CYPRESS_DASHBOARD_URL"
          else
            MESSAGE="$MESSAGE. No se pudo obtener la URL del último test de Cypress."
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"$MESSAGE\"}" $SLACK_WEBHOOK
        shell: bash
