name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARD_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress --version

      - name: Run Cypress tests with recording
        continue-on-error: true
        run: |
          npx cypress run --record --key $CYPRESS_RECORD_KEY | tee cypress_output.txt

      - name: Print Cypress output for debugging
        run: cat cypress_output.txt
